# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ede23656362d1c3986c4e46c614edee97ebe66b6f804bb104d5e6b80de13aa65be48a21f8d6e6303633b3744b4d7f17073128b7fc0a40ba7ae5eb0b4a787364

test:
  secret_key_base: 0db474b94459fa779101612abb8d21aaad31da8548773d0cc5a38e0ebc0835ff4432c368625390e1716637e8bf8b4b6dfa8d5cb3d10be3ca93b3dc41acff9eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
